version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mysql+mysqlconnector://root:mysecretpassword@db/todo_db
    # This command overrides the Dockerfile's CMD. It waits for the DB,
    # creates the tables, and then starts the server.
    command: >
      sh -c "
        echo 'Waiting for database to be ready...'
        sleep 15 &&
        echo 'Database ready! Creating tables...'
        echo 'from app import db; db.create_all()' | flask shell &&
        echo 'Tables created! Starting Flask app...'
        flask run --host=0.0.0.0
      "
    depends_on:
      - db

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=todo_db
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: